repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "--without-hashes", "--without-urls", "-o", "requirements.txt"]
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "--without-hashes", "--without-urls", "--with", "test", "-o", "requirements-test.txt"]
        verbose: true
  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
    - id: black
      language_version: python3.8
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true