repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.2'
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "--without-hashes", "--without-urls", "-o", "requirements.txt"]
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "--without-hashes", "--without-urls", "--with", "test", "-o", "requirements-test.txt"]
        verbose: true
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black